# Matches Scores Dataset Exploratory Data Analysis (EDA)

## Import Libraries

In [192]:
import numpy as np 
import pandas as pd

## Read CSV

In [193]:
df = pd.read_csv('../data/raw_data/matches_scores.csv')

## Check data types and missing values

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3006 entries, 0 to 3005
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   League      3006 non-null   object
 1   Week        3006 non-null   object
 2   Date        3006 non-null   object
 3   Home Team   3006 non-null   object
 4   Home Goals  2962 non-null   object
 5   Away Team   3006 non-null   object
 6   Away Goals  2962 non-null   object
 7   Season      3006 non-null   object
dtypes: object(8)
memory usage: 188.0+ KB

## Display the first few rows of the dataset

In [195]:
df.head()

,League,Week,Date,Home Team,Home Goals,Away Team,Away Goals,Season
0,Süper Lig,Round 1,05/08/22,İstanbulspor,0,Trabzonspor,2,22/23
1,Süper Lig,Round 1,06/08/22,Sivasspor,1,Gaziantep,1,22/23
2,Süper Lig,Round 1,06/08/22,Beşiktaş,1,Kayserispor,0,22/23
3,Süper Lig,Round 1,07/08/22,Karagümrük,2,Alanyaspor,4,22/23
4,Süper Lig,Round 1,07/08/22,Giresunspor,2,Adana DS,3,22/23

## Show Original Column Names

In [196]:
print("Original Column Names:")
print(df.columns.tolist())

Original Column Names:
['League', 'Week', 'Date', 'Home Team', 'Home Goals', 'Away Team', 'Away Goals', 'Season']

## Clean Column Names

In [197]:
df.columns = [col.lower().replace(" ", "_").replace(".", "").replace("-", "_") for col in df.columns]

## Show Cleaned Column Names

In [198]:
print("\nCleaned Column Names:")
print(df.columns.tolist())

Cleaned Column Names:
['league', 'week', 'date', 'home_team', 'home_goals', 'away_team', 'away_goals', 'season']

## Converting Columns

### Adding 'league_id' From 'league' Column

In [199]:
# Lig isimlerini league_id'ye dönüştürme eşlemesi
league_mapping = {
    'Süper Lig': 'tr1',
    '1.Lig': 'tr2',
    'PKO BP Ekstraklasa': 'pl1'
}

# Yeni league_id sütununu oluştur
df['league_id'] = df['league'].map(league_mapping)

# Orijinal league sütununu sil
df.drop('league', axis=1, inplace=True)

# Sütunları yeniden düzenle: league_id en başta olacak şekilde
cols = ['league_id'] + [col for col in df.columns if col != 'league_id']
df = df[cols]

In [200]:
df

,league_id,week,date,home_team,home_goals,away_team,away_goals,season
0,tr1,Round 1,05/08/22,İstanbulspor,0,Trabzonspor,2,22/23
1,tr1,Round 1,06/08/22,Sivasspor,1,Gaziantep,1,22/23
2,tr1,Round 1,06/08/22,Beşiktaş,1,Kayserispor,0,22/23
3,tr1,Round 1,07/08/22,Karagümrük,2,Alanyaspor,4,22/23
4,tr1,Round 1,07/08/22,Giresunspor,2,Adana DS,3,22/23
...,...,...,...,...,...,...,...,...
3001,pl1,Round 34,24/05/25,Legia,-,Stal Mielec,-,24/25
3002,pl1,Round 34,24/05/25,Puszcza,-,Śląsk,-,24/25
3003,pl1,Round 34,24/05/25,Radomiak,-,Motor,-,24/25
3004,pl1,Round 34,24/05/25,Raków,-,Widzew Łódź,-,24/25
3005,pl1,Round 34,24/05/25,Zagłębie L.,-,Cracovia,-,24/25

### Converting 'week' Column

In [201]:

# Replace " Round " with "Week " in the 'week' column
df['week'] = df['week'].str.replace('Round ', 'Week ', regex=False)
df['week'] = df['week'].str.replace('Qualification round ', 'Playoff ', regex=False)

# Display the updated DataFrame (optional)
print(df['week'].head())

0    Week 1
1    Week 1
2    Week 1
3    Week 1
4    Week 1
Name: week, dtype: object

### Converting 'date' Column to Date Format

In [202]:
# Convert 'date' column to datetime (handling day/month/year format)
# 1. First ensure proper date formatting
df['date'] = pd.to_datetime(
    df['date'].str.strip(),
    format='%d/%m/%y',
    errors='coerce'
).dt.date  # Convert to date-only (no time component)

# Optional: Format the datetime back to a clean string (e.g., "2025-05-24")
# df['date'] = df['date'].dt.strftime('%Y-%m-%d')

# Check the result
print(df['date'].head())

0    2022-08-05
1    2022-08-06
2    2022-08-06
3    2022-08-07
4    2022-08-07
Name: date, dtype: object

### Checking 'home_team' and 'away_team'

In [203]:
# Get unique teams in 'home_team' and 'away_team'
unique_home_teams = df['home_team'].unique()
unique_away_teams = df['away_team'].unique()

print("Unique Home Teams:", unique_home_teams)
print("Unique Away Teams:", unique_away_teams)

Unique Home Teams: ['İstanbulspor' 'Sivasspor' 'Beşiktaş' 'Karagümrük' 'Giresunspor'
 'Antalyaspor' 'Başakşehir' 'Fenerbahçe' 'Ankaragücü' 'Trabzonspor'
 'Kayserispor' 'Adana DS' 'Galatasaray' 'Gaziantep' 'Ümraniyespor'
 'Alanyaspor' 'Konyaspor' 'Kasımpaşa' 'Hatayspor' 'Antalyasporx2'
 'Galatasarayx2' 'Başakşehirx2' 'Pendikspor' 'Rizespor' 'Samsunspor'
 'Karagümrükx2' 'Bodrum' 'Göztepe' 'Eyüpspor' 'Konyasporx2' 'Altay'
 'Manisa' 'Gençlerbirliği' 'Sakaryaspor' 'Adanaspor' 'Erzurumspor'
 'Boluspor' 'Beykoz Anadolu' 'Altınordu' 'Keçiörengücü' 'Yeni Malatyaspor'
 'Denizlispor' 'Erzurumsporx2' 'Bandırmaspor' 'Yeni Malatyasporx2'
 'Kocaelispor' 'Şanlıurfaspor' 'Çorum' 'Manisax2' 'Erokspor' 'Iğdır'
 'Amed' 'Kocaelisporx2' 'Bandırmasporx2' 'Raków' 'Zagłębie L.' 'Lech'
 'Jagiellonia' 'Korona' 'Radomiak' 'Wisła Płock' 'Pogoń' 'Górnik'
 'Warta Poznań' 'Cracovia' 'Legia' 'Miedź' 'Piast' 'Śląsk' 'Lechia'
 'Stal Mielec' 'Widzew Łódź' 'Jagielloniax2' 'Radomiak x2' 'Ruch Chorzów'
 'ŁKS Łódź' 'Puszcza' 'GKS Katowice' 'Motor']
Unique Away Teams: ['Trabzonspor' 'Gaziantep' 'Kayserispor' 'Alanyaspor' 'Adana DS'
 'Galatasaray' 'Kasımpaşa' 'Ümraniyespor' 'Konyaspor' 'Hatayspor'
 'İstanbulspor' 'Sivasspor' 'Giresunspor' 'Ankaragücü' 'Antalyaspor'
 'Beşiktaş' 'Başakşehir' 'Fenerbahçe' 'Karagümrük' 'İstanbulsporx2'
 'Samsunspor' 'Rizespor' 'Pendikspor' 'Adana DSx3' 'Fenerbahçex2'
 'Pendiksporx2' 'Göztepe' 'Eyüpspor' 'Bodrum' 'Kayserisporx2'
 'Sivassporx2' 'Rizesporx2' 'Boluspor' 'Keçiörengücü' 'Denizlispor'
 'Altınordu' 'Yeni Malatyaspor' 'Beykoz Anadolu' 'Gençlerbirliği'
 'Bandırmaspor' 'Sakaryaspor' 'Altay' 'Adanaspor' 'Erzurumspor'
 'Eyüpsporx2' 'Manisa' 'Denizlisporx2' 'Bandırmasporx2' 'Manisax2' 'Çorum'
 'Şanlıurfaspor' 'Kocaelispor' 'Gençlerbirliğix2' 'Sakaryasporx2'
 'Erokspor' 'Iğdır' 'Amed' 'Kocaelisporx2' 'Yeni Malatyasporx2' 'Iğdırx2'
 'Amedx2' 'Ankaragücüx2' 'Warta Poznań' 'Śląsk' 'Stal Mielec' 'Piast'
 'Legia' 'Miedź' 'Lechia' 'Widzew Łódź' 'Cracovia' 'Wisła Płock' 'Korona'
 'Zagłębie L.' 'Lech' 'Raków' 'Pogoń' 'Górnik' 'Radomiak' 'Jagiellonia'
 'Śląskx3' 'ŁKS Łódź' 'Ruch Chorzów' 'Puszcza' 'Ruch Chorzówx2' 'Śląskx2'
 'Radomiak x2' 'Motor' 'GKS Katowice' 'Górnikx2']

### Converting 'home_team' and 'away_team'

In [204]:
# Create a mapping dictionary from the correct team names in your reference data
team_name_mapping = {
    # Süper Lig teams
    'Galatasarayx2': 'Galatasaray',
    'Fenerbahçe': 'Fenerbahce',
    'Fenerbahçex2': 'Fenerbahce',
    'Beşiktaş': 'Besiktas JK',
    'Başakşehir': 'Basaksehir FK',
    'Başakşehirx2': 'Basaksehir FK',
    'Trabzonspor': 'Trabzonspor',
    'Adana DS': 'Adana Demirspor',
    'Adana DSx3': 'Adana Demirspor',
    'Gaziantep': 'Gaziantep FK',
    'Karagümrük': 'Fatih Karagümrük',
    'Karagümrükx2': 'Fatih Karagümrük',
    'Göztepe': 'Göztepe',
    'Eyüpspor': 'Eyüpspor',
    'Eyüpsporx2': 'Eyüpspor',
    'Pendikspor': 'Pendikspor',
    'Pendiksporx2': 'Pendikspor',
    'Rizespor': 'Caykur Rizespor',
    'Rizesporx2': 'Caykur Rizespor',
    'Samsunspor': 'Samsunspor',
    'Kasımpaşa': 'Kasimpasa',
    'Antalyaspor': 'Antalyaspor',
    'Antalyasporx2': 'Antalyaspor',
    'Alanyaspor': 'Alanyaspor',
    'Konyaspor': 'Konyaspor',
    'Konyasporx2': 'Konyaspor',
    'Sivasspor': 'Sivasspor',
    'Sivassporx2': 'Sivasspor',
    'Kayserispor': 'Kayserispor',
    'Kayserisporx2': 'Kayserispor',
    'Hatayspor': 'Hatayspor',
    'İstanbulspor': 'İstanbulspor',
    'İstanbulsporx2': 'İstanbulspor',
    'Giresunspor': 'Giresunspor',
    'Ankaragücü': 'Ankaragücü',
    'Ankaragücüx2': 'Ankaragücü',
    'Ümraniyespor': 'Ümraniyespor',
    
    # 1. Lig teams
    'Bodrum': 'Bodrum FK',
    'Manisa': 'Manisa FK',
    'Manisax2': 'Manisa FK',
    'Gençlerbirliği': 'Gençlerbirliği SK',
    'Gençlerbirliğix2': 'Gençlerbirliği SK',
    'Sakaryaspor': 'Sakaryaspor',
    'Sakaryasporx2': 'Sakaryaspor',
    'Adanaspor': 'Adanaspor',
    'Erzurumspor': 'Erzurumspor FK',
    'Erzurumsporx2': 'Erzurumspor FK',
    'Boluspor': 'Boluspor',
    'Beykoz Anadolu': 'Beykoz Anadolu',
    'Altınordu': 'Altınordu',
    'Keçiörengücü': 'Ankara Keçiörengücü',
    'Yeni Malatyaspor': 'Yeni Malatyaspor',
    'Yeni Malatyasporx2': 'Yeni Malatyaspor',
    'Denizlispor': 'Denizlispor',
    'Denizlisporx2': 'Denizlispor',
    'Bandırmaspor': 'Bandırmaspor',
    'Bandırmasporx2': 'Bandırmaspor',
    'Kocaelispor': 'Kocaelispor',
    'Kocaelisporx2': 'Kocaelispor',
    'Şanlıurfaspor': 'Şanlıurfaspor',
    'Çorum': 'Çorum FK',
    'Erokspor': 'Esenler Erokspor',
    'Iğdır': 'Iğdır FK',
    'Iğdırx2': 'Iğdır FK',
    'Amed': 'Amed SK',
    'Amedx2': 'Amed SK',
    
    # Polish Ekstraklasa teams
    'Raków': 'Raków Częstochowa',
    'Zagłębie L.': 'Zaglebie Lubin',
    'Lech': 'Lech Poznan',
    'Jagiellonia': 'Jagiellonia Bialystok',
    'Jagielloniax2': 'Jagiellonia Bialystok',
    'Korona': 'Korona Kielce',
    'Radomiak': 'Radomiak Radom',
    'Radomiak x2': 'Radomiak Radom',
    'Wisła Płock': 'Wisła Płock',
    'Pogoń': 'Pogon Szczecin',
    'Górnik': 'Górnik Zabrze',
    'Górnikx2': 'Górnik Zabrze',
    'Warta Poznań': 'Warta Poznań',
    'Cracovia': 'Cracovia',
    'Legia': 'Legia Warszawa',
    'Miedź': 'Miedź',
    'Piast': 'Piast Gliwice',
    'Śląsk': 'Slask Wroclaw',
    'Śląskx2': 'Slask Wroclaw',
    'Śląskx3': 'Slask Wroclaw',
    'Lechia': 'Lechia Gdansk',
    'Stal Mielec': 'Stal Mielec',
    'Widzew Łódź': 'Widzew Lodz',
    'ŁKS Łódź': 'ŁKS Łódź',
    'Ruch Chorzów': 'Ruch Chorzów',
    'Ruch Chorzówx2': 'Ruch Chorzów',
    'Puszcza': 'Puszcza Niepolomice',
    'GKS Katowice': 'GKS Katowice',
    'Motor': 'Motor Lublin'
}

# Apply the mapping to both home_team and away_team columns
df['home_team'] = df['home_team'].map(team_name_mapping).fillna(df['home_team'])
df['away_team'] = df['away_team'].map(team_name_mapping).fillna(df['away_team'])

# Verify the changes
print("Unique Home Teams after standardization:", df['home_team'].unique())
print("Unique Away Teams after standardization:", df['away_team'].unique())

Unique Home Teams after standardization: ['İstanbulspor' 'Sivasspor' 'Besiktas JK' 'Fatih Karagümrük' 'Giresunspor'
 'Antalyaspor' 'Basaksehir FK' 'Fenerbahce' 'Ankaragücü' 'Trabzonspor'
 'Kayserispor' 'Adana Demirspor' 'Galatasaray' 'Gaziantep FK'
 'Ümraniyespor' 'Alanyaspor' 'Konyaspor' 'Kasimpasa' 'Hatayspor'
 'Pendikspor' 'Caykur Rizespor' 'Samsunspor' 'Bodrum FK' 'Göztepe'
 'Eyüpspor' 'Altay' 'Manisa FK' 'Gençlerbirliği SK' 'Sakaryaspor'
 'Adanaspor' 'Erzurumspor FK' 'Boluspor' 'Beykoz Anadolu' 'Altınordu'
 'Ankara Keçiörengücü' 'Yeni Malatyaspor' 'Denizlispor' 'Bandırmaspor'
 'Kocaelispor' 'Şanlıurfaspor' 'Çorum FK' 'Esenler Erokspor' 'Iğdır FK'
 'Amed SK' 'Raków Częstochowa' 'Zaglebie Lubin' 'Lech Poznan'
 'Jagiellonia Bialystok' 'Korona Kielce' 'Radomiak Radom' 'Wisła Płock'
 'Pogon Szczecin' 'Górnik Zabrze' 'Warta Poznań' 'Cracovia'
 'Legia Warszawa' 'Miedź' 'Piast Gliwice' 'Slask Wroclaw' 'Lechia Gdansk'
 'Stal Mielec' 'Widzew Lodz' 'Ruch Chorzów' 'ŁKS Łódź'
 'Puszcza Niepolomice' 'GKS Katowice' 'Motor Lublin']
Unique Away Teams after standardization: ['Trabzonspor' 'Gaziantep FK' 'Kayserispor' 'Alanyaspor' 'Adana Demirspor'
 'Galatasaray' 'Kasimpasa' 'Ümraniyespor' 'Konyaspor' 'Hatayspor'
 'İstanbulspor' 'Sivasspor' 'Giresunspor' 'Ankaragücü' 'Antalyaspor'
 'Besiktas JK' 'Basaksehir FK' 'Fenerbahce' 'Fatih Karagümrük'
 'Samsunspor' 'Caykur Rizespor' 'Pendikspor' 'Göztepe' 'Eyüpspor'
 'Bodrum FK' 'Boluspor' 'Ankara Keçiörengücü' 'Denizlispor' 'Altınordu'
 'Yeni Malatyaspor' 'Beykoz Anadolu' 'Gençlerbirliği SK' 'Bandırmaspor'
 'Sakaryaspor' 'Altay' 'Adanaspor' 'Erzurumspor FK' 'Manisa FK' 'Çorum FK'
 'Şanlıurfaspor' 'Kocaelispor' 'Esenler Erokspor' 'Iğdır FK' 'Amed SK'
 'Warta Poznań' 'Slask Wroclaw' 'Stal Mielec' 'Piast Gliwice'
 'Legia Warszawa' 'Miedź' 'Lechia Gdansk' 'Widzew Lodz' 'Cracovia'
 'Wisła Płock' 'Korona Kielce' 'Zaglebie Lubin' 'Lech Poznan'
 'Raków Częstochowa' 'Pogon Szczecin' 'Górnik Zabrze' 'Radomiak Radom'
 'Jagiellonia Bialystok' 'ŁKS Łódź' 'Ruch Chorzów' 'Puszcza Niepolomice'
 'Motor Lublin' 'GKS Katowice']

### Adding 'home_team_id' and 'away_team_id' Columns

In [205]:
ref_df = pd.read_csv('../data/raw_data/football_teams.csv')

# Create team-to-ID mapping from reference data
team_id_map = ref_df.set_index('team_name')['team_id'].to_dict()

# Filter out matches where either home or away team is missing
original_count = len(df)
df = df[df['home_team'].isin(team_id_map) & df['away_team'].isin(team_id_map)].copy()
filtered_count = len(df)

print(f"Filtered out {original_count - filtered_count} matches with missing team IDs")

# Map team IDs for remaining teams
df['home_team_id'] = df['home_team'].map(team_id_map).astype(int)
df['away_team_id'] = df['away_team'].map(team_id_map).astype(int)

# Verify
print("\nRemaining team ID assignments:")
print(df[['home_team', 'home_team_id']].drop_duplicates().sort_values('home_team_id'))
print(df[['away_team', 'away_team_id']].drop_duplicates().sort_values('away_team_id'))

Filtered out 457 matches with missing team IDs

Remaining team ID assignments:
                  home_team  home_team_id
44              Galatasaray             1
7                Fenerbahce             2
2               Besiktas JK             3
9               Trabzonspor             4
6             Basaksehir FK             5
326         Caykur Rizespor             6
710                 Göztepe             7
714                Eyüpspor             8
17                Kasimpasa             9
333              Samsunspor            10
5               Antalyaspor            11
15               Alanyaspor            12
16                Konyaspor            13
1                 Sivasspor            14
10              Kayserispor            15
20                Hatayspor            16
13             Gaziantep FK            17
705               Bodrum FK            18
11          Adana Demirspor            19
2079         Legia Warszawa            20
2069            Lech Poznan            21
2094      Raków Częstochowa            22
2070  Jagiellonia Bialystok            23
2082          Slask Wroclaw            24
2078               Cracovia            25
2068         Zaglebie Lubin            26
2074         Pogon Szczecin            27
2083          Lechia Gdansk            28
2075          Górnik Zabrze            29
2081          Piast Gliwice            30
2095            Widzew Lodz            31
2084            Stal Mielec            32
2071          Korona Kielce            33
2702           Motor Lublin            34
2090         Radomiak Radom            35
2697           GKS Katowice            36
2407    Puszcza Niepolomice            37
8                Ankaragücü            38
3          Fatih Karagümrük            39
0              İstanbulspor            40
1705                Amed SK            41
1367            Kocaelispor            42
1066           Bandırmaspor            43
1053               Boluspor            44
14             Ümraniyespor            45
1052         Erzurumspor FK            46
1068      Gençlerbirliği SK            47
1057    Ankara Keçiörengücü            48
1699       Esenler Erokspor            49
1701               Iğdır FK            50
1397               Çorum FK            51
318              Pendikspor            52
1045              Manisa FK            53
1092              Adanaspor            54
1050            Sakaryaspor            55
1399          Şanlıurfaspor            56
1059       Yeni Malatyaspor            57
                  away_team  away_team_id
5               Galatasaray             1
17               Fenerbahce             2
15              Besiktas JK             3
0               Trabzonspor             4
16            Basaksehir FK             5
320         Caykur Rizespor             6
700                 Göztepe             7
703                Eyüpspor             8
6                 Kasimpasa             9
319              Samsunspor            10
14              Antalyaspor            11
3                Alanyaspor            12
8                 Konyaspor            13
11                Sivasspor            14
2               Kayserispor            15
9                 Hatayspor            16
1              Gaziantep FK            17
714               Bodrum FK            18
26          Adana Demirspor            19
2071         Legia Warszawa            20
2103            Lech Poznan            21
2081      Raków Częstochowa            22
2092  Jagiellonia Bialystok            23
2068          Slask Wroclaw            24
2075               Cracovia            25
2079         Zaglebie Lubin            26
2082         Pogon Szczecin            27
2095          Lechia Gdansk            28
2083          Górnik Zabrze            29
2070          Piast Gliwice            30
2074            Widzew Lodz            31
2069            Stal Mielec            32
2078          Korona Kielce            33
2705           Motor Lublin            34
2084         Radomiak Radom            35
2706           GKS Katowice            36
2386    Puszcza Niepolomice            37
13               Ankaragücü            38
23         Fatih Karagümrük            39
10             İstanbulspor            40
1693                Amed SK            41
1381            Kocaelispor            42
1093           Bandırmaspor            43
1045               Boluspor            44
7              Ümraniyespor            45
1060         Erzurumspor FK            46
1053      Gençlerbirliği SK            47
1046    Ankara Keçiörengücü            48
1689       Esenler Erokspor            49
1692               Iğdır FK            50
1386               Çorum FK            51
330              Pendikspor            52
1079              Manisa FK            53
1059              Adanaspor            54
1075            Sakaryaspor            55
1376          Şanlıurfaspor            56
1049       Yeni Malatyaspor            57

In [206]:
df

,league_id,week,date,home_team,home_goals,away_team,away_goals,season,home_team_id,away_team_id
0,tr1,Week 1,2022-08-05,İstanbulspor,0,Trabzonspor,2,22/23,40,4
1,tr1,Week 1,2022-08-06,Sivasspor,1,Gaziantep FK,1,22/23,14,17
2,tr1,Week 1,2022-08-06,Besiktas JK,1,Kayserispor,0,22/23,3,15
3,tr1,Week 1,2022-08-07,Fatih Karagümrük,2,Alanyaspor,4,22/23,39,12
5,tr1,Week 1,2022-08-07,Antalyaspor,0,Galatasaray,1,22/23,11,1
...,...,...,...,...,...,...,...,...,...,...
3001,pl1,Week 34,2025-05-24,Legia Warszawa,-,Stal Mielec,-,24/25,20,32
3002,pl1,Week 34,2025-05-24,Puszcza Niepolomice,-,Slask Wroclaw,-,24/25,37,24
3003,pl1,Week 34,2025-05-24,Radomiak Radom,-,Motor Lublin,-,24/25,35,34
3004,pl1,Week 34,2025-05-24,Raków Częstochowa,-,Widzew Lodz,-,24/25,22,31
3005,pl1,Week 34,2025-05-24,Zaglebie Lubin,-,Cracovia,-,24/25,26,25

### Converting 'home_goals' and 'away_goals' Columns to Integer

In [207]:
# Convert goals columns to integers, preserving NaN values
df['home_goals'] = pd.to_numeric(df['home_goals'], errors='coerce').astype('Int64')
df['away_goals'] = pd.to_numeric(df['away_goals'], errors='coerce').astype('Int64')

# Verify the conversion
print("Data types after conversion:")
print(df[['home_goals', 'away_goals']].dtypes)

# Sample output to verify values
print("\nSample goal values:")
print(df[['home_team', 'home_goals', 'away_team', 'away_goals']].head())

Data types after conversion:
home_goals    Int64
away_goals    Int64
dtype: object

Sample goal values:
          home_team  home_goals     away_team  away_goals
0      İstanbulspor           0   Trabzonspor           2
1         Sivasspor           1  Gaziantep FK           1
2       Besiktas JK           1   Kayserispor           0
3  Fatih Karagümrük           2    Alanyaspor           4
5       Antalyaspor           0   Galatasaray           1

In [208]:
df

,league_id,week,date,home_team,home_goals,away_team,away_goals,season,home_team_id,away_team_id
0,tr1,Week 1,2022-08-05,İstanbulspor,0,Trabzonspor,2,22/23,40,4
1,tr1,Week 1,2022-08-06,Sivasspor,1,Gaziantep FK,1,22/23,14,17
2,tr1,Week 1,2022-08-06,Besiktas JK,1,Kayserispor,0,22/23,3,15
3,tr1,Week 1,2022-08-07,Fatih Karagümrük,2,Alanyaspor,4,22/23,39,12
5,tr1,Week 1,2022-08-07,Antalyaspor,0,Galatasaray,1,22/23,11,1
...,...,...,...,...,...,...,...,...,...,...
3001,pl1,Week 34,2025-05-24,Legia Warszawa,<NA>,Stal Mielec,<NA>,24/25,20,32
3002,pl1,Week 34,2025-05-24,Puszcza Niepolomice,<NA>,Slask Wroclaw,<NA>,24/25,37,24
3003,pl1,Week 34,2025-05-24,Radomiak Radom,<NA>,Motor Lublin,<NA>,24/25,35,34
3004,pl1,Week 34,2025-05-24,Raków Częstochowa,<NA>,Widzew Lodz,<NA>,24/25,22,31
3005,pl1,Week 34,2025-05-24,Zaglebie Lubin,<NA>,Cracovia,<NA>,24/25,26,25

### Adding 'home_footballer_id' and 'away_footballer_id' Column

In [209]:
footballer_df = pd.read_csv('../data/raw_data/footballers.csv')

# Clean market_value column and convert to numeric
def clean_market_value(value):
    if pd.isna(value):
        return 0
    value = value.replace('€', '').replace('m', '000000').replace('k', '000')
    return float(value.split(' ')[0])

footballer_df['market_value_numeric'] = footballer_df['market_value'].apply(clean_market_value)

# Get the highest market value player for each team
top_players = footballer_df.sort_values('market_value_numeric', ascending=False)\
                          .drop_duplicates('team_id')

# Create a team_id to footballer_id mapping
team_to_footballer = top_players.set_index('team_id')['footballer_id'].to_dict()

# Find max existing footballer_id
max_footballer_id = footballer_df['footballer_id'].max()

# Handle missing team_ids in matches
all_team_ids = set(df['home_team_id']).union(set(df['away_team_id']))
missing_teams = [tid for tid in all_team_ids if tid not in team_to_footballer]

# Assign new footballer_ids for missing teams starting from max_footballer_id + 1
if missing_teams:
    print(f"Assigning new footballer IDs starting from {max_footballer_id + 1} for {len(missing_teams)} teams")
    for i, team_id in enumerate(missing_teams, 1):
        team_to_footballer[team_id] = max_footballer_id + i

# Add footballer_id columns to matches
df['home_footballer_id'] = df['home_team_id'].map(team_to_footballer)
df['away_footballer_id'] = df['away_team_id'].map(team_to_footballer)

# Verify
print("\nSample of added footballer IDs:")
print(df[['home_team', 'home_team_id', 'home_footballer_id', 
                 'away_team', 'away_team_id', 'away_footballer_id']].head())

Sample of added footballer IDs:
          home_team  home_team_id  home_footballer_id     away_team  \
0      İstanbulspor            40                1109   Trabzonspor
1         Sivasspor            14                 391  Gaziantep FK
2       Besiktas JK             3                  65   Kayserispor
3  Fatih Karagümrük            39                1068    Alanyaspor
5       Antalyaspor            11                 310   Galatasaray

   away_team_id  away_footballer_id
0             4                 117
1            17                 468
2            15                 407
3            12                 327
5             1                  14

In [210]:
df

,league_id,week,date,home_team,home_goals,away_team,away_goals,season,home_team_id,away_team_id,home_footballer_id,away_footballer_id
0,tr1,Week 1,2022-08-05,İstanbulspor,0,Trabzonspor,2,22/23,40,4,1109,117
1,tr1,Week 1,2022-08-06,Sivasspor,1,Gaziantep FK,1,22/23,14,17,391,468
2,tr1,Week 1,2022-08-06,Besiktas JK,1,Kayserispor,0,22/23,3,15,65,407
3,tr1,Week 1,2022-08-07,Fatih Karagümrük,2,Alanyaspor,4,22/23,39,12,1068,327
5,tr1,Week 1,2022-08-07,Antalyaspor,0,Galatasaray,1,22/23,11,1,310,14
...,...,...,...,...,...,...,...,...,...,...,...,...
3001,pl1,Week 34,2025-05-24,Legia Warszawa,<NA>,Stal Mielec,<NA>,24/25,20,32,565,875
3002,pl1,Week 34,2025-05-24,Puszcza Niepolomice,<NA>,Slask Wroclaw,<NA>,24/25,37,24,1001,663
3003,pl1,Week 34,2025-05-24,Radomiak Radom,<NA>,Motor Lublin,<NA>,24/25,35,34,969,930
3004,pl1,Week 34,2025-05-24,Raków Częstochowa,<NA>,Widzew Lodz,<NA>,24/25,22,31,604,839
3005,pl1,Week 34,2025-05-24,Zaglebie Lubin,<NA>,Cracovia,<NA>,24/25,26,25,707,696

### Adding 'is_played' Column

In [211]:
# Create is_played column - True if both goals exist, False otherwise
df['is_played'] = df['home_goals'].notna() & df['away_goals'].notna()

# Convert from bool to boolean type (pandas extension type)
df['is_played'] = df['is_played'].astype('boolean')

# Verify the results
print("Value counts for is_played:")
print(df['is_played'].value_counts(dropna=False))

print("\nSample rows:")
print(df[['home_team', 'home_goals', 'away_team', 'away_goals', 'is_played']].sample(5))

Value counts for is_played:
True     2262
False     287
<NA>        0
Name: is_played, dtype: Int64

Sample rows:
           home_team  home_goals          away_team  away_goals  is_played
2516  Zaglebie Lubin           1        Widzew Lodz           1       True
2955  Pogon Szczecin        <NA>  Raków Częstochowa        <NA>      False
1993       Adanaspor        <NA>       İstanbulspor        <NA>      False
549       Ankaragücü           0          Sivasspor           0       True
158       Ankaragücü           2        Kayserispor           1       True

### Adding 'match_id' Column

In [212]:
# Add sequential match_id starting from 1
df.insert(0, 'match_id', range(1, len(df) + 1))

# Verify the results
print("DataFrame with match_id:")
print(df[['match_id', 'home_team', 'away_team']].head())

print("\nData types:")
print(df.dtypes.head())

DataFrame with match_id:
   match_id         home_team     away_team
0         1      İstanbulspor   Trabzonspor
1         2         Sivasspor  Gaziantep FK
2         3       Besiktas JK   Kayserispor
3         4  Fatih Karagümrük    Alanyaspor
5         5       Antalyaspor   Galatasaray

Data types:
match_id      int64
league_id    object
week         object
date         object
home_team    object
dtype: object

## Reorder Column Order

In [213]:
# Define the column order based on SQL table structure
column_order = [
    'match_id',
    'league_id',
    'week',
    'date',
    'home_team_id',
    'home_team',
    'home_goals',
    'away_team_id',
    'away_team',
    'away_goals',
    'season',
    'home_footballer_id',
    'away_footballer_id',
    'is_played'
]

# Reorder columns
df = df[column_order]

# Verify the new column order
print("New column order:")
print(df.columns.tolist())

print("\nSample data:")
print(df.head(2))

# Ensure proper data types
print("\nDate column sample:")
print(df[['date']].head())
print("Date column type:", type(df['date'].iloc[0]))
df['is_played'] = df['is_played'].astype('boolean')  # Ensure boolean type

New column order:
['match_id', 'league_id', 'week', 'date', 'home_team_id', 'home_team', 'home_goals', 'away_team_id', 'away_team', 'away_goals', 'season', 'home_footballer_id', 'away_footballer_id', 'is_played']

Sample data:
   match_id league_id    week        date  home_team_id     home_team  \
0         1       tr1  Week 1  2022-08-05            40  İstanbulspor
1         2       tr1  Week 1  2022-08-06            14     Sivasspor

   home_goals  away_team_id     away_team  away_goals season  \
0           0             4   Trabzonspor           2  22/23
1           1            17  Gaziantep FK           1  22/23

   home_footballer_id  away_footballer_id  is_played
0                1109                 117       True
1                 391                 468       True

Date column sample:
         date
0  2022-08-05
1  2022-08-06
2  2022-08-06
3  2022-08-07
5  2022-08-07
Date column type: <class 'datetime.date'>

In [214]:
df

,match_id,league_id,week,date,home_team_id,home_team,home_goals,away_team_id,away_team,away_goals,season,home_footballer_id,away_footballer_id,is_played
0,1,tr1,Week 1,2022-08-05,40,İstanbulspor,0,4,Trabzonspor,2,22/23,1109,117,True
1,2,tr1,Week 1,2022-08-06,14,Sivasspor,1,17,Gaziantep FK,1,22/23,391,468,True
2,3,tr1,Week 1,2022-08-06,3,Besiktas JK,1,15,Kayserispor,0,22/23,65,407,True
3,4,tr1,Week 1,2022-08-07,39,Fatih Karagümrük,2,12,Alanyaspor,4,22/23,1068,327,True
5,5,tr1,Week 1,2022-08-07,11,Antalyaspor,0,1,Galatasaray,1,22/23,310,14,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001,2545,pl1,Week 34,2025-05-24,20,Legia Warszawa,<NA>,32,Stal Mielec,<NA>,24/25,565,875,False
3002,2546,pl1,Week 34,2025-05-24,37,Puszcza Niepolomice,<NA>,24,Slask Wroclaw,<NA>,24/25,1001,663,False
3003,2547,pl1,Week 34,2025-05-24,35,Radomiak Radom,<NA>,34,Motor Lublin,<NA>,24/25,969,930,False
3004,2548,pl1,Week 34,2025-05-24,22,Raków Częstochowa,<NA>,31,Widzew Lodz,<NA>,24/25,604,839,False
3005,2549,pl1,Week 34,2025-05-24,26,Zaglebie Lubin,<NA>,25,Cracovia,<NA>,24/25,707,696,False

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2549 entries, 0 to 3005
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            2549 non-null   int64
 1   league_id           2549 non-null   object
 2   week                2549 non-null   object
 3   date                2549 non-null   object
 4   home_team_id        2549 non-null   int32
 5   home_team           2549 non-null   object
 6   home_goals          2262 non-null   Int64
 7   away_team_id        2549 non-null   int32
 8   away_team           2549 non-null   object
 9   away_goals          2262 non-null   Int64
 10  season              2549 non-null   object
 11  home_footballer_id  2549 non-null   int64
 12  away_footballer_id  2549 non-null   int64
 13  is_played           2549 non-null   boolean
dtypes: Int64(2), boolean(1), int32(2), int64(3), object(6)
memory usage: 268.8+ KB

## Save to CSV File

In [216]:
df.to_csv('../data/processed_data/matches_scores_structured.csv', index=False)

## Checking the New CSV File

In [217]:
df1 = pd.read_csv("../data/processed_data/matches_scores_structured.csv")
df1

,match_id,league_id,week,date,home_team_id,home_team,home_goals,away_team_id,away_team,away_goals,season,home_footballer_id,away_footballer_id,is_played
0,1,tr1,Week 1,2022-08-05,40,İstanbulspor,0.0,4,Trabzonspor,2.0,22/23,1109,117,True
1,2,tr1,Week 1,2022-08-06,14,Sivasspor,1.0,17,Gaziantep FK,1.0,22/23,391,468,True
2,3,tr1,Week 1,2022-08-06,3,Besiktas JK,1.0,15,Kayserispor,0.0,22/23,65,407,True
3,4,tr1,Week 1,2022-08-07,39,Fatih Karagümrük,2.0,12,Alanyaspor,4.0,22/23,1068,327,True
4,5,tr1,Week 1,2022-08-07,11,Antalyaspor,0.0,1,Galatasaray,1.0,22/23,310,14,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,2545,pl1,Week 34,2025-05-24,20,Legia Warszawa,NaN,32,Stal Mielec,NaN,24/25,565,875,False
2545,2546,pl1,Week 34,2025-05-24,37,Puszcza Niepolomice,NaN,24,Slask Wroclaw,NaN,24/25,1001,663,False
2546,2547,pl1,Week 34,2025-05-24,35,Radomiak Radom,NaN,34,Motor Lublin,NaN,24/25,969,930,False
2547,2548,pl1,Week 34,2025-05-24,22,Raków Częstochowa,NaN,31,Widzew Lodz,NaN,24/25,604,839,False
2548,2549,pl1,Week 34,2025-05-24,26,Zaglebie Lubin,NaN,25,Cracovia,NaN,24/25,707,696,False

In [218]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2549 entries, 0 to 2548
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            2549 non-null   int64
 1   league_id           2549 non-null   object
 2   week                2549 non-null   object
 3   date                2549 non-null   object
 4   home_team_id        2549 non-null   int64
 5   home_team           2549 non-null   object
 6   home_goals          2262 non-null   float64
 7   away_team_id        2549 non-null   int64
 8   away_team           2549 non-null   object
 9   away_goals          2262 non-null   float64
 10  season              2549 non-null   object
 11  home_footballer_id  2549 non-null   int64
 12  away_footballer_id  2549 non-null   int64
 13  is_played           2549 non-null   bool
dtypes: bool(1), float64(2), int64(5), object(6)
memory usage: 261.5+ KB